module.exports = 
	genes = 
		'Prehistoric Art': 'prehistoric-art'
		'Graphic Design': 'graphic-design'
		'Outdoor Art': 'outdoor-art'
		'Performance Art': 'performance-art'
		'Watercolor': 'watercolor'
		'Altarpiece': 'altarpiece'
		'Mail Art': 'mail-art'
		'Lightbox': 'lightbox'
		'Handscroll': 'handscroll'
		'Hanging Scroll': 'hanging-scroll'
		'Installation Art': 'installation-art'
		'Sound Art': 'sound-art'
		'Digital Art': 'digital-art'
		'Chrome-Plated': 'chrome-plated'
		'Encaustic': 'encaustic'
		'Textile Arts': 'textile-arts'
		'Use of Ephemeral Materials': 'use-of-ephemeral-materials'
		'East Asian Calligraphy': 'east-asian-calligraphy'
		'Typography': 'typography'
		'Hyperrealism': 'hyperrealism'
		'Use of Vintage Imagery': 'use-of-vintage-imagery'
		'Paper Cut-Outs': 'paper-cut-outs'
		'Organic Material': 'organic-material'
		'Use of Precious Materials': 'use-of-precious-materials'
		'Use of Common Materials': 'use-of-common-materials'
		'Color Theory': 'color-theory'
		'Site Specific Art': 'site-specific-art'
		'Glitch Aesthetic': 'glitch-aesthetic'
		'Digital as Manual': 'digital-as-manual'
		'Endurance Art': 'endurance-art'
		'Automatism': 'automatism'
		'Art That Plays With Scale': 'art-that-plays-with-scale'
		'Research as Art': 'research-as-art'
		'Modernizing of Traditional Technique': 'modernizing-of-traditional-technique'
		'Sfumato': 'sfumato'
		'Oil on Copper': 'oil-on-copper'
		'Chiaroscuro': 'chiaroscuro'
		'Intentionally Exposed Canvas': 'intentionally-exposed-canvas'
		'Altered and Substituted Canvases': 'altered-and-substituted-canvases'
		'Photorealistic': 'photorealistic'
		'Impasto': 'impasto'
		'En plein air': 'en-plein-air'
		'Monochrome Painting': 'monochrome-painting'
		'Trompe l’oeil': 'trompe-loeil'
		'Oil Painting': 'oil-painting'
		'History Painting': 'history-painting'
		'Caravaggesque': 'caravaggesque'
		'Rembrandtesque': 'rembrandtesque'
		'Tondo': 'tondo'
		'Tempera': 'tempera'
		'Heavily-layered Painting': 'heavily-layered-painting'
		'Picassoesque': 'picassoesque'
		'Oil on Panel': 'oil-on-panel'
		'Topographic Photography': 'topographic-photography'
		'Time-Lapse Cinematography': 'time-lapse-cinematography'
		'Photographs of Surfaces': 'photographs-of-surfaces'
		'Documentary Photography': 'documentary-photography'
		'Fashion Photography': 'fashion-photography'
		'Long Exposure': 'long-exposure'
		'Large-Scale Photography': 'large-scale-photography'
		'Camera Obscura': 'camera-obscura'
		'Abstract Photography': 'abstract-photography'
		'Manipulated Photography': 'manipulated-photography'
		'Staged Photography': 'staged-photography'
		'Photomontage': 'photomontage'
		'Photogram': 'photogram'
		'Street Photography': 'street-photography'
		'Snapshot Aesthetic': 'snapshot-aesthetic'
		'Shallow Depth of Field': 'shallow-depth-of-field'
		'Color Photography': 'color-photography'
		'Photograph as Material': 'photograph-as-material'
		'Extruded Design': 'extruded-design'
		'Bentwood': 'bentwood'
		'Intricately Sculpted': 'intricately-sculpted'
		'Polychrome Sculpture': 'polychrome-sculpture'
		'Soft Sculpture': 'soft-sculpture'
		'Kinetic Sculpture': 'kinetic-sculpture'
		'Computer-Aided Manufacturing': 'computer-aided-manufacturing'
		'Reduced-Scale Architecture': 'reduced-scale-architecture'
		'Open Form Sculpture': 'open-form-sculpture'
		'Large-Scale Sculpture': 'large-scale-sculpture'
		'Silkscreen': 'silkscreen-1'
		'Lithograph': 'lithograph-1'
		'Embossed Paper': 'embossed-paper'
		'Dense Composition': 'dense-composition'
		'Layered Images': 'layered-images'
		'Scattered Composition': 'scattered-composition'
		'Extreme Angle': 'extreme-angle'
		'Aerial View': 'aerial-view'
		'Emphasis on Linear Perspective': 'emphasis-on-linear-perspective'
		'Allover Composition': 'allover-composition'
		'Long Distance and Deep Distance': 'long-distance-and-deep-distance'
		'Frontal and Straight-On Perspective': 'frontal-and-straight-on-perspective'
		'Radiating Lines': 'radiating-lines'
		'Calligraphic': 'calligraphic'
		'Biomorphic': 'biomorphic'
		'Psychedelic': 'psychedelic'
		'Pixelated': 'pixelated'
		'Irregular Linear Forms': 'irregular-linear-forms'
		'Primary Abstraction': 'primary-abstraction'
		'Curvilinear Forms': 'curvilinear-forms'
		'Stained Glass Effect': 'stained-glass-effect'
		'Viscous Forms': 'viscous-forms'
		'Fragmented Geometry': 'fragmented-geometry'
		'Marbleized': 'marbleized'
		'Linear Forms': 'linear-forms'
		'Columns and Totems': 'columns-and-totems'
		'Tangled Forms': 'tangled-forms'
		'Irregular Curvilinear Forms': 'irregular-curvilinear-forms'
		'Divisionist': 'divisionist'
		'Contour Line': 'contour-line'
		'Imitated Material': 'imitated-material'
		'Delicate Materials': 'delicate-materials'
		'Color Gradient': 'color-gradient'
		'Pastel Colors': 'pastel-colors'
		'Earth Tones': 'earth-tones'
		'Craftsmanship and Design': 'craftsmanship-and-design'
		'Sustainable Design': 'sustainable-design'
		'Non-Functional Design': 'non-functional-design'
		'Contemporary Gothic': 'contemporary-gothic'
		'Contemporary Grotesque': 'contemporary-grotesque'
		'Contemporary Graphic Realism': 'contemporary-graphic-realism'
		'Contemporary Surrealistic': 'contemporary-surrealistic'
		'Contemporary Modernist-Type Photography': 'contemporary-modernist-type-photography-1'
		'Contemporary Academic Realism': 'contemporary-academic-realism'
		'Contemporary Fact versus Fiction': 'contemporary-fact-versus-fiction'
		'Contemporary Realist Portrait Photography': 'contemporary-realist-portrait-photography'
		'Contemporary Faux Naïf': 'contemporary-faux-naif'
		'Contemporary Archaeological': 'contemporary-archaeological'
		'Contemporary Traces of Memory': 'contemporary-traces-of-memory-1'
		'Contemporary Vintage Photography': 'contemporary-vintage-photography'
		'Political Minimalism': 'political-minimalism'
		'Contemporary Participation': 'contemporary-participation'
		'Contemporary Pop': 'contemporary-pop'
		'Contemporary DIY': 'contemporary-diy'
		'Contemporary Color Fields': 'contemporary-color-fields'
		'Contemporary Conceptualism': 'contemporary-conceptualism'
		'Post-Internet Art': 'post-internet-art'
		'Emerging Art': 'emerging-art'
		'Mimicking Ruined Materials': 'mimicking-ruined-materials'
		'Contemporary Figurative Drawing': 'contemporary-figurative-drawing'
		'Contemporary Re-creations': 'contemporary-re-creations-1'
		'Contemporary Portrait Painting': 'contemporary-portrait-painting'
		'Contemporary Ceramics': 'contemporary-ceramics'
		'Contemporary Portrait Photography': 'contemporary-portrait-photography'
		'Contemporary Figurative Painting': 'contemporary-figurative-painting'
		'Contemporary Use of Textiles': 'contemporary-use-of-textiles-1'
		'Zaire School of Popular Painting': 'zaire-school-of-popular-painting'
		'Fluxus': 'fluxus'
		'Medieval Art': 'medieval-art'
		'Bengal School of Art': 'bengal-school-of-art'
		'Art Deco': 'art-deco'
		'Art Informel': 'art-informel'
		'Art Nouveau': 'art-nouveau'
		'East Village Art': 'east-village-art'
		'Fauvism': 'fauvism'
		'Folk Art': 'folk-art'
		'Group Zero': 'group-zero'
		'Hudson River School': 'hudson-river-school'
		'Harlem Renaissance': 'harlem-renaissance'
		'Luminism': 'luminism'
		'Nabis': 'nabis'
		'Nouveau Réalisme': 'nouveau-realisme'
		'Pictorialism': 'pictorialism'
		'Purism': 'purism'
		'Social Realism': 'social-realism'
		'Surrealism': 'surrealism'
		'Young British Artists (YBAs)': 'young-british-artists-ybas'
		'Feminist Art': 'feminist-art'
		'Baroque': 'baroque'
		'Mannerism': 'mannerism'
		'Conceptual Art': 'conceptual-art'
		'Dutch and Flemish': 'dutch-and-flemish'
		'Barbizon School': 'barbizon-school'
		'Modern Photography': 'modern-photography'
		'The Pictures Generation': 'the-pictures-generation'
		'Op Art': 'op-art'
		'School of London': 'school-of-london'
		'Political Pop': 'political-pop'
		'American Regionalism': 'american-regionalism'
		'American Mid-Century Design': 'american-mid-century-design'
		'American Modern Design': 'american-modern-design'
		'Union des Artistes Modernes': 'union-des-artistes-modernes'
		'Neo-Impressionism': 'neo-impressionism'
		'New Deal / WPA': 'new-deal-slash-wpa'
		'Arte Povera': 'arte-povera'
		'Arts and Crafts Movement': 'arts-and-crafts-movement'
		'Ashcan School': 'ashcan-school'
		'"Bad Painting"': 'bad-painting'
		'Bauhaus': 'bauhaus'
		'Color Field Painting': 'color-field-painting'
		'Constructivism': 'constructivism'
		'Cubism': 'cubism'
		'Dada': 'dada'
		'De Stijl': 'de-stijl'
		'Gutai': 'gutai'
		'Futurism': 'futurism'
		'Impressionism': 'impressionism'
		'Neo-Dada': 'neo-dada'
		'Neo-Expressionism': 'neo-expressionism'
		'Mexican Muralism': 'mexican-muralism'
		'Neue Sachlichkeit': 'neue-sachlichkeit'
		'New York School': 'new-york-school'
		'Outsider Art': 'outsider-art'
		'Post-Impressionism': 'post-impressionism'
		'Pointillism': 'pointillism'
		'Postminimalism': 'postminimalism'
		'Romanticism': 'romanticism'
		'Pittura Metafisica': 'pittura-metafisica'
		'Socialist Realism': 'socialist-realism'
		'Synchromism': 'synchromism'
		'Tonalism': 'tonalism'
		'Viennese Actionism': 'viennese-actionism'
		'Byzantine Art': 'byzantine-art'
		'Suprematism': 'suprematism'
		'Japonisme': 'japonisme'
		'Group f/64': 'group-f-slash-64'
		'Abstraction-Création': 'abstraction-creation'
		'Early Renaissance': 'early-renaissance'
		'Nineteenth Century French Realism': 'nineteenth-century-french-realism'
		'American Realism': 'american-realism'
		'American Modernism': 'american-modernism'
		'Post-World War I European Classicism': 'post-world-war-i-european-classicism'
		'Cynical Realism': 'cynical-realism'
		'85 New Wave': '85-new-wave'
		'Spatialism': 'spatialism'
		'The Blue Rider': 'the-blue-rider'
		'Vienna Secession': 'vienna-secession'
		'Art Brut': 'art-brut'
		'German Expressionism': 'german-expressionism'
		'Capitalist Realism': 'capitalist-realism'
		'Land Art': 'land-art'
		'Funk Art': 'funk-art'
		'Pop Art': 'pop-art'
		'New Topographics': 'new-topographics'
		'Dau Al Set': 'dau-al-set'
		'Pre-Raphaelites': 'pre-raphaelites'
		'Die Brücke': 'die-brucke'
		'New Leipzig School': 'new-leipzig-school'
		'Relational Aesthetics': 'relational-aesthetics'
		'Rococo': 'rococo'
		'High Renaissance': 'high-renaissance'
		'Northern Renaissance': 'northern-renaissance'
		'Bay Area Figurative Art': 'bay-area-figurative-art'
		'Early Medieval Art': 'early-medieval-art'
		'Romanesque Art': 'romanesque-art'
		'Light and Space Movement': 'light-and-space-movement'
		'Neoclassicism': 'neoclassicism'
		'Precisionism': 'precisionism'
		'American Impressionism': 'american-impressionism'
		'Neo-Geo': 'neo-geo'
		'Mono-ha': 'mono-ha'
		'Cluj School': 'cluj-school'
		'Neo-Conceptualism': 'neo-conceptualism'
		'Dusseldorf School of Photography': 'dusseldorf-school-of-photography'
		'The New Fauves': 'the-new-fauves'
		'New British Sculpture': 'new-british-sculpture'
		'Grand Manner': 'grand-manner'
		'Post-Painterly Abstraction': 'post-painterly-abstraction'
		'New American Color Photography': 'new-american-color-photography'
		'Concrete Art': 'concrete-art'
		'Orphism': 'orphism'
		'Neo-Concrete Art': 'neo-concrete-art'
		'Brutalism': 'brutalism'
		'Neo-Plasticism': 'neo-plasticism'
		'Post-World War II School of Paris': 'post-world-war-ii-school-of-paris'
		'Venetian School': 'venetian-school'
		'American Studio Craft Movement': 'american-studio-craft-movement'
		'Post-war French Design': 'post-war-french-design'
		'Postmodern Architecture & Design': 'postmodern-architecture-and-design'
		'The Aesthetic Movement': 'the-aesthetic-movement'
		'New American Documentary Photography': 'new-american-documentary-photography'
		'Pre-World War II School of Paris': 'pre-world-war-ii-school-of-paris'
		'Black Mountain College': 'black-mountain-college'
		'Progressive Artists\' Movement': 'progressive-artists-movement'
		'Danube School': 'danube-school'
		'Abstract Expressionism': 'abstract-expressionism'
		'Minimalism': 'minimalism'
		'Graffiti/Street Art': 'graffiti-slash-street-art'
		'Orientalism': 'orientalism'
		'Beijing East Village': 'beijing-east-village'
		'Action Painting': 'action-painting'
		'Transavanguardia': 'transavanguardia'
		'CalArts': 'calarts'
		'Rinpa School': 'rinpa-school'
		'Kanō School': 'kano-school'
		'Ukiyo-e': 'ukiyo-e'
		'Washington Color School': 'washington-color-school'
		'Old Master Drawings and Prints': 'old-master-drawings-and-prints'
		'Afrofuturism': 'afrofuturism'
		'Spiral Group': 'spiral-group'
		'Black Arts Movement': 'black-arts-movement'
		'Nul Group': 'nul-group'
		'The Stars Art Group (Xing Xing)': 'the-stars-art-group-xing-xing'
		'Chicago Imagists': 'chicago-imagists'
		'19th Century German Realism': '19th-century-german-realism'
		'Post-\'70s Ego Generation': 'post-70s-ego-generation'
		'Chicano Art': 'chicano-art'
		'Net Art': 'net-art'
		'Yale University School of Art': 'yale-university-school-of-art'
		'Shang Dynasty': 'shang-dynasty'
		'Edo Art': 'edo-art'
		'Ancient Egypt': 'ancient-egypt'
		'Hellenistic Art': 'hellenistic-art'
		'Igbo (Ibo) Art': 'igbo-ibo-art'
		'Melanesia, Micronesia and Polynesia': 'melanesia-micronesia-and-polynesia'
		'Mayan Art and Architecture': 'mayan-art-and-architecture'
		'Song Dynasty': 'song-dynasty'
		'Art of the Ivory Coast': 'art-of-the-ivory-coast'
		'Aboriginal Art': 'aboriginal-art'
		'Roman Art and Architecture': 'roman-art-and-architecture'
		'Greek Art and Architecture': 'greek-art-and-architecture'
		'Indonesian Art': 'indonesian-art'
		'Himalayan Art': 'himalayan-art'
		'Native American, First Nations, and Alaska Native Art': 'native-american-first-nations-and-alaska-native-art'
		'Pre-Columbian Art': 'pre-columbian-art'
		'Han Dynasty': 'han-dynasty'
		'Etruscan Art': 'etruscan-art'
		'Qing Dynasty': 'qing-dynasty'
		'Meiji Art': 'meiji-art'
		'Ming Dynasty': 'ming-dynasty'
		'Thai Art': 'thai-art'
		'Syrian Art': 'syrian-art'
		'Art of the Congo': 'art-of-the-congo'
		'Mughal Art': 'mughal-art'
		'Guatemalan Art': 'guatemalan-art'
		'Yoruba Art': 'yoruba-art'
		'Mesopotamian Art': 'mesopotamian-art'
		'Tang Dynasty': 'tang-dynasty'
		'Ottoman Art': 'ottoman-art'
		'Benin Art': 'benin-art'
		'Western Zhou Dynasty': 'western-zhou-dynasty'
		'Art of the Upper Paleolithic': 'art-of-the-upper-paleolithic'
		'Aztec Art': 'aztec-art'
		'Cambodian Art': 'cambodian-art'
		'Art of Burma': 'art-of-burma'
		'Hopi Art': 'hopi-art'
		'Yup\'ik Art': 'yupik-art'
		'Kushan Empire': 'kushan-empire'
		'Minoan Art': 'minoan-art'
		'Papua New Guinea Art': 'papua-new-guinea-art'
		'Eastern Zhou Dynasty': 'eastern-zhou-dynasty'
		'Heian Period': 'heian-period'
		'Cheyenne Art': 'cheyenne-art'
		'Taiwanese Art': 'taiwanese-art'
		'Yuan Dynasty': 'yuan-dynasty'
		'Phoenician Art': 'phoenician-art'
		'Mycenaean Art': 'mycenaean-art'
		'Bamileke Art': 'bamileke-art'
		'Mende Art': 'mende-art'
		'Asante Art': 'asante-art'
		'Moche Art': 'moche-art'
		'Art of Tonga': 'art-of-tonga'
		'Sui Dynasty': 'sui-dynasty'
		'Yombe Art': 'yombe-art'
		'Iban Art': 'iban-art'
		'Maranao Art': 'maranao-art'
		'Yaka Art': 'yaka-art'
		'Celtic Art': 'celtic-art'
		'Oku Art': 'oku-art'
		'Mbole Art': 'mbole-art'
		'Traditional African Art': 'traditional-african-art'
		'Traditional Oceanic Art': 'traditional-oceanic-art'
		'Northern and Southern Dynasties': 'northern-and-southern-dynasties'
		'Christian Art and Architecture': 'christian-art-and-architecture'
		'Buddhist Art and Architecture': 'buddhist-art-and-architecture'
		'Hindu Art and Architecture': 'hindu-art-and-architecture'
		'Islamic Art and Architecture': 'islamic-art-and-architecture'
		'French Design': 'french-design'
		'Scandinavian Design': 'scandinavian-design'
		'Italian Design': 'italian-design'
		'Emerging Design': 'emerging-design'
		'Traditional Scroll Painting': 'traditional-scroll-painting'
		'Intaglio': 'intaglio'
		'Greek and Roman Art and Architecture': 'greek-and-roman-art-and-architecture'
		'Arts of Africa, Oceania, and the Americas': 'arts-of-africa-oceania-and-the-americas'
		'Modern and Contemporary Design': 'modern-and-contemporary-design'
		'Post-War European Art': 'post-war-european-art'
		'Contemporary Middle Eastern Art': 'contemporary-middle-eastern-art'
		'Landscape Photography': 'landscape-photography'
		'Old Masters': 'old-masters'
		'Post-War American Art': 'post-war-american-art'
		'Contemporary Chinese Art': 'contemporary-chinese-art'
		'Women Artists': 'women-artists'
		'Contemporary Photography': 'contemporary-photography'
		'Contemporary Latin American Art': 'contemporary-latin-american-art'
		'Contemporary British Art': 'contemporary-british-art'
		'Contemporary Asian Art': 'contemporary-asian-art'
		'Contemporary Indian Art': 'contemporary-indian-art'
		'19th Century American Art': '19th-century-american-art'
		'Contemporary Canadian Art': 'contemporary-canadian-art'
		'Contemporary Turkish Art': 'contemporary-turkish-art'
		'Tokyo Artists': 'tokyo-artists'
		'Latin American Art': 'latin-american-art'
		'Contemporary Scandinavian Art': 'contemporary-scandinavian-art'
		'Contemporary African Art': 'contemporary-african-art'
		'Japanese Photography': 'japanese-photography'
		'California Art': 'california-art'
		'Brooklyn Artists': 'brooklyn-artists'
		'Berlin Artists': 'berlin-artists'
		'Beijing Artists': 'beijing-artists'
		'London Artists': 'london-artists'
		'Los Angeles Artists': 'los-angeles-artists'
		'New York Artists': 'new-york-artists'
		'Paris Artists': 'paris-artists'
		'San Francisco Artists': 'san-francisco-artists'
		'Black-and-white Photography': 'black-and-white-photography'
		'Black and White Photography': 'black-and-white-photography'
		'Traditional Photography Prints': 'traditional-photography-prints'
		'Cyanotype': 'traditional-photography-prints'
		'Daguerreotype': 'traditional-photography-prints'
		'Albumen Print': 'traditional-photography-prints'
		'Ambrotype': 'traditional-photography-prints'
		'Palladium Print': 'traditional-photography-prints'
		'Gum Bichromate': 'traditional-photography-prints'
		'Multiple Exposures': 'multiple-exposure'
		'Gold Leaf and Gilding': 'gold-leaf-and-gilding'
		'Gold Leaf': 'gold-leaf-and-gilding'
		'Gilding': 'gold-leaf-and-gilding'
		'East Asian Ink-and-Wash Painting': 'east-asian-ink-and-wash-painting'
		'Shanshui': 'east-asian-ink-and-wash-painting'
		'Modern and Contemporary Fashion Design': 'modern-and-contemporary-fashion-design'
		'Modern Fashion Design': 'modern-and-contemporary-fashion-design'
		'Contemporary Fashion Design': 'modern-and-contemporary-fashion-design'
		'Sculpture-Based Photography': 'sculpture-based-photography'
		'Sculpture Based Photography': 'sculpture-based-photography'
		'Miniature and Small-Scale Paintings': 'miniature-and-small-scale-paintings'
		'Miniature Painting': 'miniature-and-small-scale-paintings'
		'Wall Installation': 'wall-sculpture-and-installation'
		'Social Action Art': 'social-action'
		'Contemporary Glass Art': 'contemporary-glass'
